# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_rate', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_rate.Project'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='v_rate.Project'),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
