# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_rate', '0003_auto_20201027_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v_rate.Project'),
        ),
    ]
