# Generated by Django 3.1.2 on 2020-10-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_rate', '0006_auto_20201027_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='v_rate.profile'),
            preserve_default='True',
        ),
    ]
