# Generated by Django 3.1.2 on 2020-10-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_rate', '0007_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
